name: LimbusEGOGift
version: 2.0
main: me.yisang.limbusegogift.LimbusEGOGift
description: Limbus Company E.G.O Gift accessory system
api-version: "1.21.4"
commands:
  accessories:
    description: 開啟飾品欄位
    usage: /accessories
  getgift:
    description: 取得飾品
    usage: /getgift <id> [amount]
    permission: limbus.admin
  gachachest:
    description: 設定或移除抽取箱
    usage: /gachachest <set|remove>
    permission: limbus.admin
  egogift:
    description: 開啟飾品圖鑑
    usage: /egogift category
